### ISSUE TITLE
WFST for Draw

### ISSUE THREAD

**Issue by cleberar38** [getsmap/smap-responsive#100]
### WFST for Draw

Create a WFST Draw tool using geoserver.

**Comment by johanlahti** [comment]
Adding encoding support. Some weird strings cannot be sent by WFS-T without encoding the first. For instance [this one](http://www.icatserver.com/weblink2.aspx?22pimmUVKq3gk3WGgoDnig%3d%3d=G1QJQngsYTGGRsqPyyxVZg%3d%3d&K36xuyKwGHIyS9%2fMZSe9Xw%3d%3d=Upxi11T17x0q6rwMdZQiHA%3d%3d&Tj9nYD%2b6ayesUbBPaueJBA%3d%3d=0FSrunmcNa2IOKhAMGvClg%3d%3d)

Therefore, I added the possibility to encode some properties. These are specified in the plugin's option encodeKeys:
```
// options for plugin in Editor.js or in the config file

// Option 1: Specify columns/keys
encodeKeys: ["pics", "urls"]  // Values with these keys will be encoded before sent to the WFS-T service

// Option 2: No encoding at all
encodeKeys: null   // Nothing will be encoded

// Option 3: All attributes encoded
encodeKeys: "*"  // All attribute values will be encoded before send to WFS-T
```

All attributes which are encoded will also be decoded before visualised in the editing window so that we don't encode something already encoded, again and again.
