### ISSUE TITLE
Wrong url in get command

### ISSUE THREAD

**Issue by johammp** [getsmap/smap-responsive#196]
When saving position in map the wrong get-url is used.
In the prod. environment the url is https://kartor.malmo.se/gkkundservicedev should be changed to gkkundservice

**Comment by johanlahti** [comment]
The previous commit should solve the issue.

**Comment by johammp** [comment]
Did a test on Friday but still get error.

**Comment by johanlahti** [comment]
OK. I thought the dev-site should still call ```gkkundservice.test.malmo.se``` for fetching features. But I can see now that service directs me to an error page. I have now changed so that the dev version calls the same service as the prod. However, the prod-version (domain gkkundservice.malmo.se) was already calling this domain from before and should have worked before I changed. Anyways, try it and close the issue if you also get it to work.

**Comment by johanlahti** [comment]
Now the proxy points to the dev version as we decided per email. Just needs to be confirmed everything is working fine.

**Comment by johammp** [comment]
Tried to save a location on the test server and everything seems to work fine!

**Comment by johanlahti** [comment]
:+1:  :cactus:  I close the issue.

**Comment by johanlahti** [comment]
Point our prod-proxy towards MMPs prod environment (right now points to dev-env).

**Comment by johanlahti** [comment]
OK. I see now that this needs to be changed on the client and not the server proxy.

**Comment by johammp** [comment]
It now works fine on prod!
